// This file is auto-generated by @hey-api/openapi-ts

export type HelloGetResponse = string;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
};