// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PollResponse = {
    bitpoll_link: string;
    start_next_poll_date: string;
    next_schafkopf_event?: string | null;
    current_poll_started: string;
};

export type SubscribeCountResponse = {
    count: number;
};

export type SubscribeRequest = {
    email: string;
};

export type SubscribeResponse = {
    email: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SubscribeToSchafkopfRoundsSubscribePostData = {
    requestBody: SubscribeRequest;
};

export type SubscribeToSchafkopfRoundsSubscribePostResponse = SubscribeResponse;

export type DeleteSubscriberFromMailingListSubscriberDeleteData = {
    email: string;
};

export type DeleteSubscriberFromMailingListSubscriberDeleteResponse = SubscribeResponse;

export type GetSubscriberCountSubscribersCountGetResponse = SubscribeCountResponse;

export type GetPollPollGetResponse = PollResponse;

export type $OpenApiTs = {
    '/subscribe': {
        post: {
            req: SubscribeToSchafkopfRoundsSubscribePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: SubscribeResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/subscriber': {
        delete: {
            req: DeleteSubscriberFromMailingListSubscriberDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: SubscribeResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/subscribers/count': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: SubscribeCountResponse;
            };
        };
    };
    '/poll': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: PollResponse;
            };
        };
    };
};
