name: Scheduler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
permissions:
  id-token: write
  contents: read

jobs:
  build-ebg_scanner:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - validation
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082113759242:role/github_oidc_role
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build -f ./ebg_scanner/Dockerfile -t 082113759242.dkr.ecr.eu-central-1.amazonaws.com/ebg_scanner-lambda:latest .
          docker push 082113759242.dkr.ecr.eu-central-1.amazonaws.com/ebg_scanner-lambda:latest
  build-whatsapp_client:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - validation
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082113759242:role/github_oidc_role
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build --platform linux/amd64 -f ./whatsapp-client/Dockerfile -t 082113759242.dkr.ecr.eu-central-1.amazonaws.com/whatsapp_scheduler-lambda:latest ./whatsapp-client
          docker push 082113759242.dkr.ecr.eu-central-1.amazonaws.com/whatsapp_scheduler-lambda:latest
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build-ebg_scanner
      - build-whatsapp_client
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082113759242:role/github_oidc_role
          aws-region: eu-central-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      - name: Initialize Terraform
        working-directory: infrastructure
        run: terraform init
      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve
